### ISSUE TITLE
API Pop-Up: #8 of 10

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/mihomeguru.com#1]
@codextiny
Please add API functionality to [this new site.](https://mihomeguru.com/)

Credentials:
U: [support@homeowner.ai](mailto:support@homeowner.ai)
PW: M!l3st0nesL@bs

- Update search bar with API functionality
- Add pop up form to Get Started Button in header on home page
- Add pop up form to CTA button in pre-footer on home page

**Comment by Faizan-Ramzan** [comment]
@shannonbaldwin 

done from our side, please check

**Comment by shannonbaldwin** [comment]
@Faizan-Ramzan Sorry, this was not here for you. Please add pop-up to get started text in header.

![image](https://github.com/user-attachments/assets/11a45284-90e8-4bc5-9a2e-77a9f2a3a96d)

**Comment by shannonbaldwin** [comment]
@Faizan-Ramzan Can you please show me how to remove this border on the home page?
![image](https://github.com/user-attachments/assets/28790b46-7d6d-4910-8d24-764093516578)

**Comment by Faizan-Ramzan** [comment]
> @Faizan-Ramzan Sorry, this was not here for you. Please add pop-up to get started text in header.
> 
> ![image](https://private-user-images.githubusercontent.com/167017886/386677458-11a45284-90e8-4bc5-9a2e-77a9f2a3a96d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTc1OTksIm5iZiI6MTczMTY5NzI5OSwicGF0aCI6Ii8xNjcwMTc4ODYvMzg2Njc3NDU4LTExYTQ1Mjg0LTkwZTgtNGJjNS05YTJlLTc3YTlmMmEzYTk2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxOTAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGU0ZGMzYmYwYzZkOGZkZjA1ODU3MzA3MWI1OGZhZWUyMWIwYzU0NzhiNDEwZWM0ZTgxNmE2Y2E0NzlhY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MYycAt5ULb9ntDEVP6OcWwRMJQHgFtLen-_SCRpZ7Jg)

popup added to Get started cta in header.

**Comment by Faizan-Ramzan** [comment]
> @Faizan-Ramzan Can you please show me how to remove this border on the home page? ![image](https://private-user-images.githubusercontent.com/167017886/386675866-28790b46-7d6d-4910-8d24-764093516578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTc1OTksIm5iZiI6MTczMTY5NzI5OSwicGF0aCI6Ii8xNjcwMTc4ODYvMzg2Njc1ODY2LTI4NzkwYjQ2LTdkNmQtNDkxMC04ZDI0LTc2NDA5MzUxNjU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxOTAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmU1MmQ4MGZhNzUyZDU5ZGMyMTZmNWFmZTlkZjljYzNiMjQ1ZWEwZjRiMTAxZWJlYWMxNmFjNzFlYTg1ZmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s-SpcCz1Egcz0tvljZ8F82zQ3REUr-c55XTAN-j7b4g)

this is because of "minimal skin", you cannot remove it from options, i have added custom code in advanced tab to get rid of outline.
![image](https://github.com/user-attachments/assets/e3e4d6b4-ef33-4748-a1b3-cdd065544d45)
